/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include <stdint.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  //#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
#include <stm32f4xx.h>

int main(void){

	//RCC->AHB1ENR |= (1<<0);
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN ;
	GPIOA->MODER &= ~(0b11 << (GPIO_MODER_MODE5_Pos))
	GPIOA->MODER |= (0b01 << GPIO_MODER_MODE5_Pos);
	GPIOA->ODR |= (1 << 5);





	    while(1)
	    {

	    }

}
